# Generated by Django 5.2.7 on 2025-10-01 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
