# Generated by Django 5.2.7 on 2025-10-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0002_cliente_data_cadastro_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
    ]
